name: "Auto-Approve Certain Dependency Update PRs"

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened

jobs:
  approve-pr-if-dependency-update:
    name: Approve PR if Dependency Update from GitHub Actions
    if: github.event.pull_request.user.id == 206383919 && (github.event.pull_request.title == 'Automatic Website Update' || github.event.pull_request.title == 'Automatic Forums Update')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Generate App Token
        id: app-token-generation
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5
        with:
          app-id: ${{ secrets.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}

      - name: GitHub API Call
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/pulls/${{github.event.number}}/reviews \
          --header 'authorization: Bearer ${{ github.token }}' \
          --header 'content-type: application/json' \
          -d '{"event":"APPROVE"}' \
          --fail
