name: Sync Dependencies

on:
  workflow_dispatch:
    inputs:
      dependency:
        description: "Dependency"
        required: true

concurrency:
  group: "infra-update-${{ github.event.inputs.dependency }}"
  cancel-in-progress: false

jobs:
  create_website_update_pr:
    name: Create Website Update PR
    runs-on: ubuntu-latest
    if: github.event.inputs.dependency == 'Website' || github.event.inputs.dependency == 'Forums'
    steps:
      - name: Checkout Repository
        run: git clone -b main --depth 1 --single-branch "https://git@github.com/tgstation-operations/infrastructure" .

      - name: Install Nix
        run: sh .github/workflows/install_lix.sh
        env:
          EXTRA_NIX_CONFIG: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            extra-substituters = https://nix-community.cachix.org https://attic.tgstation13.org/tgstation-infrastructure
            extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= tgstation-infrastructure:07mCKRLs4Y+ietmQ5A1Wn3hRYHVUu1vZ20xPmwMyrBA=

      - name: Generate App Token
        id: app-token-generation
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5
        with:
          app-id: ${{ secrets.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}

      - name: Update Website Flake Only
        if: github.event.inputs.dependency == 'Website'
        run: |
          nix flake update tgstation-website

      - name: Update Forums Flake Only
        if: github.event.inputs.dependency == 'Forums'
        run: |
          nix flake update tgstation-phpbb

      - name: Commit
        run: |
          git checkout -b AutomaticWebsiteUpdate
          git config user.name "tgstation-operations-ci[bot]"
          git config user.email "206383919+tgstation-operations-ci[bot]@users.noreply.github.com"
          git add flake.lock
          git commit -m "Automatic flake.lock update for ${{ github.event.inputs.dependency }} push"

      - name: Push
        run: |
          git push -f "https://tgstation-operations-ci:${{ steps.app-token-generation.outputs.token }}@github.com/tgstation-operations/infrastructure"

      - name: Open PR
        run: gh pr create -B main -H AutomaticWebsiteUpdate --title 'Automatic ${{ github.event.inputs.dependency }} Update' --body 'Created by Github actions'
        env:
          GITHUB_TOKEN: ${{ steps.app-token-generation.outputs.token }}
