name: Sync Website

on:
  workflow_dispatch:

concurrency:
  group: "infra-update"
  cancel-in-progress: false

jobs:
  create_website_update_pr:
    name: Create Website Update PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        run: git clone -b main --depth 1 --single-branch "https://git@github.com/tgstation-operations/infrastructure" .

      - name: Mount compressed fs at /nix
        shell: bash
        run: |
          dd if=/dev/zero of=./nix-store.img bs=1 count=0 seek=15G
          mkfs.btrfs -M ./nix-store.img
          sudo mkdir /nix
          sudo mount -o defaults,noatime,compress=zstd ./nix-store.img /nix

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-args: --prefer-upstream-nix

      - name: Set up Nix magic cache
        uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diagnostic-endpoint: ""

      - name: Generate App Token
        id: app-token-generation
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5
        with:
          app-id: ${{ secrets.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}

      - name: Update Website Flake Only
        run: |
          nix flake lock --update-input tgstation-website

      - name: Commit
        run: |
          git checkout -b AutomaticWebsiteUpdate
          git config user.name "tgstation-operations-ci[bot]"
          git config user.email "206383919+tgstation-operations-ci[bot]@users.noreply.github.com"
          git add flake.lock
          git commit -m "Automatic flake.lock update for website-v2 push"

      - name: Push
        run: |
          git push -f "https://tgstation-operations-ci:${{ steps.app-token-generation.outputs.token }}@github.com/tgstation-operations/infrastructure"

      - name: Open PR
        run: gh pr create -B main -H AutomaticWebsiteUpdate --title 'Automatic Website Update' --body 'Created by Github actions'
        env:
          GITHUB_TOKEN: ${{ steps.app-token-generation.outputs.token }}
